project:
  type: website

website:
  title: "How bad Washington Wizzards is"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: barplots.qmd
        text: Team comparison
      - href: player_performance.qmd
        text: Wizzards star player performance
      - href: shootpercentge.qmd
        text: Shooting performace

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true