project:
  type: website

website:
  title: "quarto_p"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: barplots.qmd
        text: Team comparison
      - href: player_performance.qmd
        text: Wizzards star player performance


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



